baseURL = "https://hugo-demo-times.pages.dev"
defaultContentLanguage = "zh"
description = "A news paper style Hugo theme" # This will be used in the meta description tag
title = "Kai Rowan, A designer"
theme = "times"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
  [markup.highlight]
    noClasses = false
    style = "dracula"

[taxonomies]
  category = "categories"
  tag = "tags"
  year = "year"

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = "content/en"
    weight = 1
  [languages.zh]
    languageName = '中文'
    contentDir = "content/zh"
    weight = 2
  [languages.fr]
    languageName = 'france'
    contentDir = "content/fr"
    weight = 3


[languages.en.params]
  description = "About me"
  reading_speed = 212

[languages.zh.params]
  description = "About me"
  reading_speed = 500

[languages.fr.params]
  description = "About me"
  reading_speed = 212

[languages.zh.menu]
  [[languages.zh.menu.main]]
    identifier = "about"
    name = "關於"
    url = "/about/"
    weight = 1
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
  headerTitle = "Kai Rowan, A designer"
  author = "Kai Rowan" # This will be used in the meta author tag and alt text of the header avatar
  mainSections = ["posts"]
  featuredPosts = 3
  motto = "About me"
  footerBottomText = "CC BY-NC-SA 4.0"
  rss = true
  email = "focusidler@gmail.com"
  # Check more theme in https://daisyui.com/docs/themes/
  lightTheme = "wireframe"
  darkTheme = "black"
  showTableOfContents = true
  showSummaryCoverInPost = true
  headerAvatar = "avatar/avatar-512x512.png"
  showPrevNextPost = true
  # byText = "Author"
  # backgroundImage = "me/background.jpg"
  # backgroundImageDark = ""
  # footer
  siteStartYear = 2024
  hasCJKLanguage = true 
  
# options
# You can use https://favicon.io/favicon-generator/ to make sure the favicon works will on all browsers and devices.
[params.favicon]
  png = "favicon/favicon-96x96.png"
  svg = "favicon/favicon.svg"
  ico = "favicon/favicon.ico"
  apple = "favicon/apple-touch-icon.png"
  manifest = "favicon/site.webmanifest"

  # Syntax highlighting
  # customSyntaxHighlighting = true

  # stickyNav = true
  # reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
  # collapseNavItems = ["posts", "categories", "tags"]
  # noDefaultSummaryCover = true

  # imageZoomableInPost = true
  # showPrevNextPost = true
  # reorderShares = ["x", "facebook", "whatsapp"]

  # [params.navItems]

  # [params.twikoo]
  # enabled = true
  # envID = ""
  # region = ""
  # lang = ""

  # [params.advanced]
  # customCSS = ["css/custom.css"]
  # customJS = []