name = 'Times'
license = 'MIT'
licenselink = 'https://github.com/yushinliou/hugo-theme-times/blob/main/LICENSE'
description = 'A news paper style Hugo theme'

homepage = 'https://github.com/yushinliou/hugo-theme-times'

demosite = 'https://hugo-demo-times.pages.dev'

tags = ['blog', 'news', 'journal', 'magazine', 'responsive', 'multilingual', 'tailwindcss', 'darkmode', "gallery", "portfolio"]
features = [
  "Minimal & Modern Design",
  "Filter posts by categories and tags",
  "Dark/light theme switch",
  "SEO friendly",
  "RSS feed",
  "Timeline archive view",
  "Responsive",
  "Favicon",
  "Multilingual",
  "Google Analytics",
  "Disqus",
  "Utterances",
  "Syntax Highlighting",
  "Customizable",
]

[author]
  name = 'Yu Shin Liou'
  homepage = 'https://focusidler.com'

[original]
  author = "Yue Yang"
  homepage = 'https://g1en.site'
  repo = 'https://github.com/g1eny0ung'

